services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=Europe/Belfast
      - PLEX_CLAIM=xxxxxxxxxxxxxxxxxxxxx
    volumes:
      - ./config:/config
      - SonosShare:/media/sonosshare
      - ./photo:/media/photo
      - ./recordings:/media/recordings
      - ./video:/media/video

volumes:
  SonosShare:
    external: true
