services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=xxxxxxxxxxxxxxxxxxxx
      # - WG_HOST=xxxxxxxxxxxxxxx
      # ⚠️ Change the Web UI Password:
      - PASSWORD=xxxxxxxxxxxxxxxxxxxxxxx

      # 💡 This is the AdGuard/Adguard Container's IP Address
      - WG_DEFAULT_DNS=192.168.1.2
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_ALLOWED_IPS=192.168.1.0/24
n   image: ghcr.io/wg-easy/wg-easy
    container_name: wireguardeasy
    volumes:
      - ~/.wireguardeasy:/etc/wireguardeasy
    ports:
      # Port of the WireGuard Easy VPN server
      - "51820:51820/udp"
      # Port of the WireGuard Easy UI
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
